export type WebsiteTheme = 'moonlight' | 'parchment' | 'ember' | 'midnight'
export type WebsiteBook = { novelId: string; title: string; description: string; cover?: string; coverDesign?: { frontImage?: string; spineImage?: string; backImage?: string; frontColor?: string; spineColor?: string; backColor?: string }; status?: string; url?: string; order: number }
export type WebsiteLink = { id: string; label: string; url: string; kind?: 'instagram' | 'x' | 'youtube' | 'github' | 'contact' | 'website' }
export type WebsitePost = { id: string; title: string; date: string; excerpt: string; url?: string; published: boolean }
export type AuthorWebsite = { id:'author-website'; version:2; kind:'author-website'; title:string; authorName:string; tagline:string; bio:string; location:string; profileImage?:string; heroImage?:string; heroEyebrow:string; intro:string; primaryCta:string; secondaryCta:string; heroQuote:string; books:WebsiteBook[]; showBookDescriptions:boolean; showBookStatus:boolean; aboutHeading:string; aboutText:string; interests:string[]; journalEnabled:boolean; posts:WebsitePost[]; links:WebsiteLink[]; theme:WebsiteTheme; accent:string; background:string; typography:'editorial'|'classic'|'modern'; heroOverlay:number; sectionSpacing:'compact'|'comfortable'|'spacious'; showMoonScribe:boolean; privacyUrl:string; contactUrl:string; published:boolean; publishedAt?:number; updatedAt:number; rev?:number; pendingSync?:boolean }
export const WEBSITE_THEMES=[{id:'moonlight',name:'Moonlight',description:'Cinematic black, muted blue and gold',swatches:['#080b0e','#12202b','#d6a64b']},{id:'parchment',name:'Parchment',description:'Warm paper, brown and antique gold',swatches:['#ede2ce','#3b2b20','#aa7730']},{id:'ember',name:'Ember',description:'Warm black, umber and copper',swatches:['#100b09','#301b13','#c87942']},{id:'midnight',name:'Midnight',description:'Deep navy, silver and muted gold',swatches:['#060910','#111b2a','#b9a875']}] as const
export function defaultAuthorWebsite(authorName=''):AuthorWebsite{return{id:'author-website',version:2,kind:'author-website',title:`${authorName||'Author'} — Official Website`,authorName,tagline:'Stories for the spaces between.',bio:'',location:'',heroEyebrow:'AUTHOR · WRITER · STORYTELLER',intro:'I write character-driven stories about resilience, discovery, and what it means to be human — even in the darkest places.',primaryCta:'Explore My Books',secondaryCta:'Read the Journal',heroQuote:'“Better stories build brighter worlds.”',books:[],showBookDescriptions:true,showBookStatus:true,aboutHeading:'About the Author',aboutText:'',interests:['Storyteller','Worldbuilder','Dreamer','Always Exploring'],journalEnabled:false,posts:[],links:[],theme:'moonlight',accent:'#d6a64b',background:'#080b0e',typography:'editorial',heroOverlay:68,sectionSpacing:'comfortable',showMoonScribe:true,privacyUrl:'/privacy',contactUrl:'mailto:',published:false,updatedAt:Date.now()}}
export function normalizeAuthorWebsite(input:Partial<AuthorWebsite>|null|undefined,authorName=''):AuthorWebsite{const base=defaultAuthorWebsite(authorName);const merged={...base,...(input||{})};return{...merged,id:'author-website',kind:'author-website',version:2,books:Array.isArray(input?.books)?input.books:[],links:Array.isArray(input?.links)?input.links:[],posts:Array.isArray(input?.posts)?input.posts:[],interests:Array.isArray(input?.interests)?input.interests:base.interests,theme:WEBSITE_THEMES.some(theme=>theme.id===merged.theme)?merged.theme:'moonlight',typography:['editorial','classic','modern'].includes(merged.typography)?merged.typography:'editorial',sectionSpacing:['compact','comfortable','spacious'].includes(merged.sectionSpacing)?merged.sectionSpacing:'comfortable',heroOverlay:Math.min(90,Math.max(20,Number(merged.heroOverlay)||68))}}
export function safeWebsiteUrl(value:string){if(value?.startsWith('/'))return value;try{const u=new URL(value);return['http:','https:','mailto:'].includes(u.protocol)?u.toString():''}catch{return''}}
