export type WebsiteTheme = 'moonlight' | 'parchment' | 'ember' | 'midnight'
export type WebsiteBook = { novelId: string; title: string; description: string; cover?: string; coverDesign?: { frontImage?: string; spineImage?: string; backImage?: string; frontColor?: string; spineColor?: string; backColor?: string }; status?: string; url?: string; order: number }
export type WebsiteLink = { id: string; label: string; url: string; kind?: 'instagram' | 'x' | 'youtube' | 'github' | 'contact' | 'website' }
export type WebsitePostStatus = 'draft' | 'review' | 'scheduled' | 'published'
export type WebsitePost = { id: string; title: string; date: string; excerpt: string; url?: string; published: boolean; status?: WebsitePostStatus; scheduledAt?: string }
export type WebsiteBlock = { id: string; kind: 'quote' | 'gallery' | 'cta' | 'newsletter'; heading: string; body: string; image?: string; url?: string; visible: boolean }
export type WebsiteSectionType = 'hero'|'books'|'about'|'journal'|'contact'|'quote'|'gallery'|'video'|'audio'|'newsletter'|'events'|'faq'|'timeline'
export type WebsiteSection = { id:string; type:WebsiteSectionType; props?:Record<string, unknown>; visible?:boolean; visibility?:{desktop?:boolean;tablet?:boolean;mobile?:boolean} }
export type WebsitePage = { id:string; name:string; slug:string; homepage?:boolean; seo?:{title?:string;description?:string;image?:string}; sections:WebsiteSection[] }
export type AuthorWebsite = { id:'author-website'; version:2; kind:'author-website'; title:string; authorName:string; tagline:string; bio:string; location:string; genres:string[]; profileImage?:string; heroImage?:string; heroEyebrow:string; intro:string; primaryCta:string; secondaryCta:string; heroQuote:string; books:WebsiteBook[]; booksView?:'shelf'|'list'; showBookDescriptions:boolean; showBookStatus:boolean; aboutHeading:string; aboutText:string; interests:string[]; journalEnabled:boolean; posts:WebsitePost[]; links:WebsiteLink[]; newsletterUrl:string; mediaKitUrl:string; theme:WebsiteTheme; accent:string; background:string; typography:'editorial'|'classic'|'modern'; heroOverlay:number; sectionSpacing:'compact'|'comfortable'|'spacious'; designPreset:'editorial'|'speculative'|'commercial'|'minimal'|'archive'; blocks:WebsiteBlock[]; pages?:WebsitePage[]; seoTitle:string; seoDescription:string; ogImage?:string; showMoonScribe:boolean; privacyUrl:string; contactUrl:string; published:boolean; publishedAt?:number; updatedAt:number; rev?:number; pendingSync?:boolean }
const DEFAULT_HERO = '/assets/moonscribebackground.png'
export function defaultWebsitePages():WebsitePage[]{return[{id:'home',name:'Home',slug:'',homepage:true,sections:[{id:'hero',type:'hero'},{id:'books',type:'books'},{id:'about',type:'about'},{id:'journal',type:'journal'}]}]}
export const WEBSITE_THEMES=[{id:'moonlight',name:'Moonlight',description:'Cinematic black, muted blue and gold',swatches:['#080b0e','#12202b','#d6a64b']},{id:'parchment',name:'Parchment',description:'Warm paper, brown and antique gold',swatches:['#ede2ce','#3b2b20','#aa7730']},{id:'ember',name:'Ember',description:'Warm black, umber and copper',swatches:['#100b09','#301b13','#c87942']},{id:'midnight',name:'Midnight',description:'Deep navy, silver and muted gold',swatches:['#060910','#111b2a','#b9a875']}] as const
export const WEBSITE_DESIGN_PRESETS=[{id:'editorial',name:'Editorial literary',description:'Warm paper, serif type, restrained motion'},{id:'speculative',name:'Dark speculative',description:'Near-black surfaces and immersive cover art'},{id:'commercial',name:'Contemporary commercial',description:'Bold type and a clear newsletter action'},{id:'minimal',name:'Minimalist author',description:'Generous space and book-first hierarchy'},{id:'archive',name:'Archive / catalogue',description:'Structured metadata and collected works'}] as const
export function defaultAuthorWebsite(authorName=''):AuthorWebsite{return{id:'author-website',version:2,kind:'author-website',title:`${authorName||'Author'} — Official Website`,authorName,tagline:'Stories for the spaces between.',bio:'',location:'',genres:[],profileImage:undefined,heroImage:DEFAULT_HERO,heroEyebrow:'AUTHOR · WRITER · STORYTELLER',intro:'I write character-driven stories about resilience, discovery, and what it means to be human — even in the darkest places.',primaryCta:'Explore My Books',secondaryCta:'Read the Journal',heroQuote:'“Better stories build brighter worlds.”',books:[],booksView:'shelf',showBookDescriptions:true,showBookStatus:true,aboutHeading:'About the Author',aboutText:'',interests:['Storyteller','Worldbuilder','Dreamer','Always Exploring'],journalEnabled:false,posts:[],links:[],newsletterUrl:'',mediaKitUrl:'',theme:'moonlight',accent:'#d6a64b',background:'#080b0e',typography:'editorial',heroOverlay:68,sectionSpacing:'comfortable',designPreset:'editorial',blocks:[],pages:defaultWebsitePages(),seoTitle:'',seoDescription:'',ogImage:undefined,showMoonScribe:true,privacyUrl:'/privacy',contactUrl:'mailto:',published:false,updatedAt:Date.now()}}
export function normalizeAuthorWebsite(input:Partial<AuthorWebsite>|null|undefined,authorName=''):AuthorWebsite{const base=defaultAuthorWebsite(authorName);const merged={...base,...(input||{})};return{...merged,id:'author-website',kind:'author-website',version:2,heroImage:input?.heroImage===undefined?base.heroImage:input.heroImage,books:Array.isArray(input?.books)?input.books:[],links:Array.isArray(input?.links)?input.links:[],posts:Array.isArray(input?.posts)?input.posts:[],interests:Array.isArray(input?.interests)?input.interests:base.interests,genres:Array.isArray(input?.genres)?input.genres:[],blocks:Array.isArray(input?.blocks)?input.blocks:[],pages:Array.isArray(input?.pages)&&input.pages.length?input.pages:base.pages,theme:WEBSITE_THEMES.some(theme=>theme.id===merged.theme)?merged.theme:'moonlight',typography:['editorial','classic','modern'].includes(merged.typography)?merged.typography:'editorial',sectionSpacing:['compact','comfortable','spacious'].includes(merged.sectionSpacing)?merged.sectionSpacing:'comfortable',designPreset:WEBSITE_DESIGN_PRESETS.some(preset=>preset.id===merged.designPreset)?merged.designPreset:'editorial',heroOverlay:Math.min(90,Math.max(20,Number(merged.heroOverlay)||68))}}
export function safeWebsiteUrl(value:string){if(value?.startsWith('/'))return value;try{const u=new URL(value);return['http:','https:','mailto:'].includes(u.protocol)?u.toString():''}catch{return''}}
