import { Resend } from 'resend'

const resend = process.env.RESEND_API_KEY ? new Resend(process.env.RESEND_API_KEY) : null
const fromAddress = process.env.RESEND_FROM || process.env.RESEND_FROM_EMAIL || 'MoonScribe <noreply@moonscribe.cc>'
const appUrl = String(process.env.PUBLIC_ORIGIN || process.env.APP_ORIGIN || 'https://moonscribe.cc').replace(/\/$/, '')
const logoUrl = process.env.MOONSCRIBE_EMAIL_LOGO_URL || `${appUrl}/icons/icon-192.png`
const escapeHtml = (value) => String(value ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;')
const paragraph = (value) => `<p style="margin:0 0 18px">${escapeHtml(value)}</p>`

function shell({ eyebrow = 'MoonScribe', title, intro, body, cta, security = false }) {
  const button = cta ? `<p style="margin:28px 0 8px"><a href="${escapeHtml(cta.href)}" style="display:inline-block;background:#d6a64b;color:#12100c;text-decoration:none;padding:14px 22px;font-weight:700;border-radius:8px;box-shadow:0 6px 16px rgba(214,166,75,.2)">${escapeHtml(cta.label)} <span style="padding-left:8px">→</span></a></p>` : ''
  const notice = security ? '<div style="border-top:1px solid #35312a;margin-top:28px;padding-top:16px;color:#aaa59b;font-size:13px">If you did not request this, you can safely ignore this message. Your account remains protected.</div>' : ''
  return `<!doctype html><html lang="en"><body style="margin:0;background:#08090d;color:#eee9dc;font-family:Arial,Helvetica,sans-serif;line-height:1.6"><div style="padding:36px 16px;background:radial-gradient(circle at 50% 0,#252014 0,transparent 34%)"><div style="max-width:620px;margin:0 auto"><header style="text-align:center;padding:8px 0 28px"><img src="${escapeHtml(logoUrl)}" width="46" height="46" alt="MoonScribe" style="display:inline-block;border:0;border-radius:14px"><div style="font-family:Georgia,serif;color:#e1b762;font-size:20px;margin-top:10px;letter-spacing:.02em">MoonScribe</div><div style="color:#827b70;font-size:11px;letter-spacing:.16em;text-transform:uppercase;margin-top:5px">Write worlds worth remembering</div></header><main style="background:#111218;border:1px solid #302d27;border-radius:16px;padding:34px 30px;box-shadow:0 18px 50px rgba(0,0,0,.3)"><div style="color:#d6a64b;text-transform:uppercase;letter-spacing:.16em;font-size:11px;font-weight:700">${escapeHtml(eyebrow)}</div><h1 style="font-family:Georgia,serif;font-weight:400;font-size:32px;line-height:1.16;margin:11px 0 18px;color:#f7f0e2">${escapeHtml(title)}</h1>${intro ? `<p style="color:#bbb6ac;margin:0 0 22px;font-size:16px">${escapeHtml(intro)}</p>` : ''}<div style="color:#d8d3c8;font-size:15px">${body}</div>${button}${notice}</main><footer style="text-align:center;color:#777681;font-size:12px;padding:24px 0">MoonScribe · <a href="${escapeHtml(appUrl)}" style="color:#b9a77f;text-decoration:none">moonscribe.cc</a> · <a href="${escapeHtml(appUrl + '/privacy')}" style="color:#b9a77f;text-decoration:none">Privacy</a> · <a href="${escapeHtml(appUrl + '/account')}" style="color:#b9a77f;text-decoration:none">Account</a><br><span style="display:inline-block;margin-top:8px">© ${new Date().getFullYear()} MoonScribe</span></footer></div></div></body></html>`
}
function compose({ to, subject, text, title, intro, body, cta, security, eyebrow }) { return sendTransactionalEmail({ to, subject, text, html: shell({ title, intro, body, cta, security, eyebrow }) }) }
export function isEmailConfigured() { return Boolean(resend) }
export async function sendTransactionalEmail({ to, subject, text, html }) { if (!resend) return { ok: false, reason: 'EMAIL_NOT_CONFIGURED' }; try { const response = await resend.emails.send({ from: fromAddress, to: Array.isArray(to) ? to : [to], subject, text, html: html || text }); if (response?.error) return { ok: false, error: response.error, reason: 'EMAIL_SEND_FAILED' }; return { ok: true, response } } catch (error) { return { ok: false, error, reason: 'EMAIL_SEND_FAILED' } } }
export function sendVerificationCode({ to, username, code, appOrigin, expiresAt }) { const expiry = expiresAt ? new Date(expiresAt).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' }) : 'soon'; return compose({ to, subject: 'Verify your MoonScribe account', title: 'Verify your email', intro: 'One small step before your library is ready.', body: paragraph(`Hello ${username || 'writer'},`) + `<p style="font-size:34px;letter-spacing:.2em;color:#e1b762;font-weight:700">${escapeHtml(code)}</p>` + paragraph(`This code expires at ${expiry}.`), text: `MoonScribe verification code: ${code}. It expires at ${expiry}. ${appOrigin || appUrl}`, security: true }) }
export function sendTwoFactorCode({ to, username, code }) { return compose({ to, subject: 'Your MoonScribe security code', title: 'Your security code', intro: 'Use this code to complete your sign-in.', body: paragraph(`Hello ${username || 'writer'},`) + `<p style="font-size:34px;letter-spacing:.2em;color:#e1b762;font-weight:700">${escapeHtml(code)}</p>`, text: `Your MoonScribe security code is ${code}.`, security: true, eyebrow: 'Account security' }) }
export function sendMagicLink({ to, username, link }) { return compose({ to, subject: 'Your MoonScribe sign-in link', title: 'Return to your stories', intro: `Hello ${username || 'writer'},`, body: paragraph('Use this secure, one-use link to open your MoonScribe library. It expires in 15 minutes.'), cta: { href: link, label: 'Open MoonScribe' }, text: `Open your MoonScribe sign-in link: ${link}. It expires in 15 minutes.`, security: true }) }
export function sendAccountUpdateEmail({ to, username, summary }) { return compose({ to, subject: 'MoonScribe account update', title: 'Account update', intro: `Hello ${username || 'writer'},`, body: paragraph(summary), text: `MoonScribe account update: ${summary}`, eyebrow: 'Account' }) }
export function sendReminderEmail({ to, username, title, message }) { return compose({ to, subject: title, title, intro: `Hello ${username || 'writer'},`, body: paragraph(message), text: `${title}\n\n${message}` }) }
