import { useEffect } from 'react'
import { Link } from 'react-router-dom'
import { POLICY_DOCUMENTS, type PolicyKey } from '../data/policies'

type PageKey = PolicyKey | 'community' | 'contact'
const extras = { community: { title: 'MoonScribe Community', summary: 'A thoughtful room for writers.', sections: [{ id: 'standard', title: 'Community standard', content: <p>Be constructive, respect unpublished work, ask before sharing another writer’s material, and critique the writing rather than the writer.</p> }] }, contact: { title: 'Contact MoonScribe', summary: 'Support, privacy, safety, and legal requests.', sections: [{ id: 'support', title: 'Support', content: <p>Open an issue in the official <a href="https://github.com/HaydenDev3/moonscribe/issues" target="_blank" rel="noreferrer">MoonScribe repository</a>. Never include passwords, recovery codes, or private manuscript text.</p> }] } }

export default function PublicPage({ page }: { page: PageKey }) {
  const policy = POLICY_DOCUMENTS[page as PolicyKey]
  const item = policy || { ...extras[page as 'community' | 'contact'], key: page, version: null, effectiveDate: null, updatedDate: null, requiresSignupConsent: false }
  useEffect(() => { document.title = `${item.title} — MoonScribe`; document.querySelector('meta[name="description"]')?.setAttribute('content', item.summary); return () => { document.title = 'MoonScribe — Novel Writing & Book Design Studio' } }, [item.title, item.summary])
  return <main className="public-page public-policy-page"><header><Link to="/" className="public-brand"><img src="/moonscribelogo.png" alt="" />MoonScribe<span>✦</span></Link><nav aria-label="Public navigation"><Link to="/">Studio</Link><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link><Link to="/contact">Contact</Link></nav></header><div className="public-policy-layout"><aside className="public-policy-toc" aria-label="On this page"><strong>On this page</strong>{item.sections.map((s) => <a key={s.id} href={`#${s.id}`}>{s.title}</a>)}</aside><article><p className="public-kicker">MoonScribe · Trust &amp; policy</p><h1>{item.title}</h1><p className="public-lead">{item.summary}</p>{item.version && <div className="public-policy-meta"><span>Version {item.version}</span><span>Effective {item.effectiveDate}</span><span>Updated {item.updatedDate}</span></div>}<div className="public-policy-review" role="note">Product-grounded draft · Please obtain independent legal review before launch.</div>{item.sections.map((s) => <section id={s.id} key={s.id}><h2>{s.title}</h2>{s.content}</section>)}<div className="public-related"><strong>Related policies</strong><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link><Link to="/cookies">Cookies</Link><Link to="/acceptable-use">Acceptable use</Link></div></article></div><footer><span>© 2026 MoonScribe</span><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link><Link to="/cookies">Cookies</Link><Link to="/acceptable-use">Acceptable use</Link></footer></main>
}
