import { useState } from 'react'
import AuthModal from './AuthModal'
import { useApp } from '../context/AppContext'
import Icon from './Icon'
export default function DesktopGateway() {
  const { continueAsGuest, hasRole, syncUsername } = useApp() as any
  const [authOpen, setAuthOpen] = useState(false)
  const betaAccess = hasRole?.('admin') || hasRole?.('developer') || hasRole?.('beta_tester')
  if (syncUsername && !betaAccess) return <main className="desktop-gateway"><div className="desktop-gateway-card"><img className="desktop-gateway-logo" src="/moonscribelogo.png" alt="MoonScribe" /><div className="desktop-gateway-kicker">PRIVATE BETA</div><h1>Desktop access is reserved.</h1><p>The MoonScribe desktop app is currently available to Beta Testers, Developers, and Admins. Your cloud library remains available in the browser.</p><button className="desktop-gateway-primary" onClick={() => window.open('https://moonscribe.cc/dashboard', '_blank', 'noopener,noreferrer')}>Open MoonScribe Cloud</button><small>Ask the MoonScribe team for desktop beta access.</small></div></main>
  return <main className="desktop-gateway"><div className="desktop-gateway-orbit" aria-hidden="true" /><div className="desktop-gateway-layout"><section className="desktop-gateway-story"><div className="desktop-gateway-kicker">MOONSCRIBE DESKTOP</div><h1>A quiet place for the stories only you can write.</h1><p>Pick up your library, shape a world, and return to the page without losing the thread.</p><div className="desktop-gateway-points"><span><Icon icon="fa-solid fa-cloud-arrow-down" /> Local-first writing</span><span><Icon icon="fa-solid fa-feather-pointed" /> Focused manuscript tools</span><span><Icon icon="fa-solid fa-shield-halved" /> Private by default</span></div></section><section className="desktop-gateway-card"><img className="desktop-gateway-logo" src="/moonscribelogo.png" alt="MoonScribe" /><div className="desktop-gateway-kicker">WELCOME BACK</div><h2>Return to your stories.</h2><p>Your library can travel with you, or stay entirely on this device.</p><button className="desktop-gateway-primary" onClick={() => setAuthOpen(true)}>Sign in to MoonScribe <Icon icon="fa-solid fa-arrow-right" /></button><button className="desktop-gateway-guest" onClick={() => void continueAsGuest?.()}>Continue offline</button><small>Google, Discord, passkeys, and email all lead to the same library.</small></section></div><AuthModal open={authOpen} onClose={() => setAuthOpen(false)} /></main>
}
