import { useState, type KeyboardEvent } from 'react'

type ElasticSliderProps = { value:number; onChange:(value:number)=>void; min?:number; max?:number; step?:number; label:string; leftIcon?:string; rightIcon?:string }

/** MoonScribe's themed adaptation of the React Bits Elastic Slider pattern. */
export default function ElasticSlider({value,onChange,min=0,max=100,step=1,label,leftIcon='fa-solid fa-volume-low',rightIcon='fa-solid fa-volume-high'}:ElasticSliderProps){
 const [active,setActive]=useState(false); const current=Math.min(max,Math.max(min,Number(value)||0)); const percent=((current-min)/Math.max(1,max-min))*100
 const adjust=(event:KeyboardEvent<HTMLDivElement>)=>{if(event.key==='ArrowLeft'||event.key==='ArrowDown'){event.preventDefault();onChange(Math.max(min,current-step))}if(event.key==='ArrowRight'||event.key==='ArrowUp'){event.preventDefault();onChange(Math.min(max,current+step))}if(event.key==='Home'){event.preventDefault();onChange(min)}if(event.key==='End'){event.preventDefault();onChange(max)}}
 return <div className="flex min-w-0 items-center gap-3" role="group" aria-label={label}><i aria-hidden="true" className={`${leftIcon} shrink-0 text-[11px] text-[var(--grey)]`}/><div className="relative flex min-w-0 flex-1 items-center py-3" onPointerDown={()=>setActive(true)} onPointerUp={()=>setActive(false)} onPointerCancel={()=>setActive(false)}><div className="pointer-events-none absolute inset-x-0 h-1 overflow-hidden rounded-full bg-[color:var(--border)]"><span className="block h-full rounded-full bg-[var(--accent)] transition-[width] duration-100" style={{width:`${percent}%`}}/></div><div className={`pointer-events-none absolute h-5 w-5 rounded-full border-2 border-[var(--surface)] bg-[var(--accent)] shadow-[0_0_0_1px_color-mix(in_srgb,var(--accent)_60%,transparent),0_3px_12px_color-mix(in_srgb,var(--accent)_35%,transparent)] transition-transform duration-200 ${active?'scale-[1.28]':'scale-100'}`} style={{left:`calc(${percent}% - 10px)`}}/><input aria-label={label} className="relative z-10 h-6 w-full cursor-grab appearance-none bg-transparent opacity-0 active:cursor-grabbing" type="range" min={min} max={max} step={step} value={current} onChange={event=>onChange(Number(event.target.value))} onFocus={()=>setActive(true)} onBlur={()=>setActive(false)} onKeyDown={adjust}/></div><i aria-hidden="true" className={`${rightIcon} shrink-0 text-[11px] text-[var(--grey)]`}/><output className="w-12 shrink-0 text-right font-mono text-sm tabular-nums text-[var(--accent)]">{current}%</output></div>
}
