import { useApp } from '../context/AppContext'
import Icon from './Icon'

type Variant = 'success' | 'info' | 'warning' | 'error' | 'milestone' | 'feature'
const classify = (message: string): Variant => /error|failed|could not|unable|payload/i.test(message) ? 'error' : /warning|limit|away|expired/i.test(message) ? 'warning' : /milestone|words today|amazing/i.test(message) ? 'milestone' : /feature|library is here/i.test(message) ? 'feature' : /sync|connection|sign/i.test(message) ? 'info' : 'success'
const config: Record<Variant, { label: string; icon: string; border: string; glow: string; text: string; bar: string }> = {
 success:{label:'SUCCESS',icon:'fa-solid fa-check',border:'border-emerald-300/30',glow:'from-emerald-400/16',text:'text-emerald-200',bar:'bg-emerald-300'}, info:{label:'INFO',icon:'fa-solid fa-circle-info',border:'border-sky-300/30',glow:'from-sky-400/16',text:'text-sky-200',bar:'bg-sky-300'}, warning:{label:'WARNING',icon:'fa-solid fa-triangle-exclamation',border:'border-amber-300/35',glow:'from-amber-400/16',text:'text-amber-200',bar:'bg-amber-300'}, error:{label:'ERROR',icon:'fa-solid fa-xmark',border:'border-rose-300/35',glow:'from-rose-400/16',text:'text-rose-200',bar:'bg-rose-300'}, milestone:{label:'MILESTONE',icon:'fa-solid fa-star',border:'border-amber-300/35',glow:'from-amber-300/16',text:'text-amber-200',bar:'bg-amber-200'}, feature:{label:'NEW FEATURE',icon:'fa-solid fa-gift',border:'border-sky-300/35',glow:'from-sky-400/16',text:'text-sky-200',bar:'bg-sky-300'} }
const glowFor = (variant: Variant) => ({ error: 'radial-gradient(circle at 12% 45%, rgba(251,113,133,.16), rgba(251,113,133,.04) 35%, transparent 65%)', success: 'radial-gradient(circle at 12% 45%, rgba(110,231,183,.14), rgba(110,231,183,.03) 35%, transparent 65%)', warning: 'radial-gradient(circle at 12% 45%, rgba(251,191,36,.14), rgba(251,191,36,.03) 35%, transparent 65%)', info: 'radial-gradient(circle at 12% 45%, rgba(125,211,252,.14), rgba(125,211,252,.03) 35%, transparent 65%)', milestone: 'radial-gradient(circle at 12% 45%, rgba(252,211,77,.14), rgba(252,211,77,.03) 35%, transparent 65%)', feature: 'radial-gradient(circle at 12% 45%, rgba(56,189,248,.14), rgba(56,189,248,.03) 35%, transparent 65%)' }[variant])
function copy(message:string, variant:Variant){ if(variant==='error') return {title: message.replace(/^.*?(payload too large)$/i,'$1').replace(/^error[: ]*/i,''), description:'Check your connection and try again.'}; if(variant==='success') return {title:message,description:'Your changes have been saved locally.'}; if(variant==='milestone') return {title:message,description:'Amazing progress — keep going!'}; if(variant==='feature') return {title:message,description:'Explore the latest MoonScribe improvements.'}; return {title:message,description:''} }
export default function Toasts(){ const {toasts, dismissToast}=useApp(); if(!toasts.length)return null; return <div className="fixed right-6 top-6 z-[9999] flex w-[min(520px,calc(100vw-2rem))] flex-col gap-3" role="status" aria-live="polite">{toasts.slice(-3).map(t=>{const variant=classify(t.msg);const p=config[variant];const text=copy(t.msg,variant);return <article key={t.id} className={`group relative min-h-[140px] overflow-hidden rounded-[22px] border ${p.border} bg-[#0c0c10]/95 px-6 py-5 text-[#f4efe7] shadow-[0_20px_70px_rgba(0,0,0,.45)] backdrop-blur-xl transition-all duration-300`}><div className="pointer-events-none absolute inset-0 opacity-80" style={{ background: glowFor(variant) }} /><div className="relative flex items-start gap-5"><div className={`mt-1 grid h-14 w-14 shrink-0 place-items-center rounded-full border border-white/20 bg-black/35 text-xl ${p.text} shadow-[0_0_22px_rgba(251,113,133,.25)]`}><Icon icon={p.icon}/></div><div className="min-w-0 flex-1 pr-8"><div className="flex items-center justify-between gap-3"><span className={`text-[10px] font-semibold uppercase tracking-[.28em] ${p.text}`}>{p.label}</span><time className="text-[10px] text-white/35">Just now</time></div><h3 className="mt-1.5 font-serif text-[17px] font-medium leading-tight text-[#f4efe7]">{text.title}</h3>{text.description&&<p className="mt-1.5 text-[13px] leading-6 text-white/50">{text.description}</p>}{t.action&&<div className="mt-4 flex flex-wrap gap-3"><button type="button" className="h-10 rounded-lg border border-white/15 bg-white/[.03] px-5 text-sm text-white/80 hover:bg-white/[.07]" onClick={()=>void t.action.run()}>{t.action.label||'Try again'}</button></div>}</div></div><button type="button" onClick={()=>dismissToast?.(t.id)} aria-label="Dismiss notification" className="absolute right-3 top-1 grid h-8 w-8 place-items-center rounded-full text-white/50 hover:bg-white/5 hover:text-white/80"><Icon icon="fa-solid fa-xmark"/></button><div className="absolute bottom-3 left-6 right-6 h-[3px] overflow-hidden rounded-full bg-white/[.06]"><div className={`h-full w-2/3 rounded-full ${p.bar} opacity-80`}/></div></article>})}</div> }
